# -*- coding: utf-8 -*-
"""dice_roller.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TcZtBNtsqTDmeZBwB6qCf3C0X7ChhlkO
"""

# Dice Roller Program
# Generates a random number between 1 and 6

import random

print("🎲 Welcome to the Dice Roller!")

roll = random.randint(1, 6)
print("You rolled a " + str(roll) + "!")